CREATE TABLE DBO_SAMPLE.REF_COUNTRY
(
    ID          INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME        VARCHAR(60),
    CODE        VARCHAR(32)     NOT NULL,
    CREATED_BY  VARCHAR(64)     NOT NULL,
    CREATED_ON  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(64)     NOT NULL,
    MODIFIED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED  BOOLEAN   DEFAULT FALSE
);
